pipeline {
    agent any
    stages {
        stage('Terraform init') {
            steps {
                echo 'Initialize Terraform'
                sh 'cd infrastructure/opa-policies/infra/ && terraform init'
            }
        }
        stage('Terraform plan') {
            steps {
                echo 'Prepare Terraform plan in JSON file'
                sh 'cd infrastructure/opa-policies/infra/ && terraform plan --out tfplan.binary'
                sh 'cd infrastructure/opa-policies/infra/ && terraform show -json tfplan.binary > tfplan.json'
            }
        }
        stage('Rego policy') {
            steps {
                echo 'Execute Rego policy'
                sh 'opa exec --decision terraform/analysis --bundle infrastructure/opa-policies/policy infrastructure/opa-policies/infra/tfplan.json'
                sh 'opa exec --decision terraform/analysis/score --bundle infrastructure/opa-policies/policy infrastructure/opa-policies/infra/tfplan.json'
                sh 'opa exec --decision terraform/analysis/allow --bundle infrastructure/opa-policies/policy infrastructure/opa-policies/infra/tfplan.json'
                sh 'opa exec --decision terraform/analysis/allow --bundle infrastructure/opa-policies/policy infrastructure/opa-policies/infra/tfplan.json | jq ".result[0].result" | grep true'
            }
        }
        stage('Terraform deploy') {
            steps {
                echo 'Deploy infrastrucutre'
                sh 'cd infrastructure/opa-policies/infra/ && terraform apply -auto-approve'
            }
        }
        stage('Localstack check') {
            steps {
                echo 'Check resources deployed in Localstack'
                sh 'aws --endpoint-url=http://localstack:4566 s3 ls'
                sh 'aws --endpoint-url=http://localstack:4566 s3 ls s3://localstack-s3-opa-example'
            }
        }
    }
}